### ISSUE TITLE
mkdir() "/usr/local/openresty/nginx/client_body_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by dove-young** [openresty/docker-openresty#120]
Docker image  `openresty/openresty:alpine` cannot start up while deploy into Kubernetes with `runAsNonRoot: true` security context

Image ID is  ` "sha256:98649cc07221ad5e30cdc72f717b11754bd128d54152f002c81605eabe4652e0"`

Error message said as this

```
kubectl logs openresty-55f8d78fdb-wm75s
chmod: /usr/local/openresty/nginx: Operation not permitted
2019/09/19 07:59:07 [emerg] 7#7: mkdir() "/usr/local/openresty/nginx/client_body_temp" failed (13: Permission denie
d)
nginx: [emerg] mkdir() "/usr/local/openresty/nginx/client_body_temp" failed (13: Permission denied)
```

It actually need to create many directories under `/usr/local/openresty/nginx` during start up
- uwsgi_temp
- scgi_temp
- proxy_temp
- fastcgi_temp
- client_body_temp

And it also failed to create `error.log` file under `/usr/local/openresty/nginx/logs`  while deploy into Kubernetes with `runAsNonRoot: true` security context

The only way I can get it up and running is to configure `clusterrolebinding` to allow  `openresty/openresty:alpine` to run as `root`.  This is an un-acceptable security context in a production environment.

**Comment by neomantra** [comment]
This is a dupe of #119.   Can you check out the solution there and see if it meets your needs?

I'll be resolving that within the next week.

**Comment by dove-young** [comment]
solution on #119 works for me.

**Comment by Robbie558** [comment]
Further to configuration of the temp directories (`uwsgi_temp` etc.) listed in this comment I had to set the pid location to use a temporary directory.

For context the `securityContext` configuration in my K8s `deployment` object was as follows, with `readOnlyRootFilesystem` **must** be set to `false`:

```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
...
  template:
  ...
  spec:
    ...
    containers:
        - name: container
          ...
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: false   
...
```
